debug: true

spring:
  output:
    ansi:
      enabled: always
  application:
    name: downstream-service

  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: http://foo

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans